eclipse/aCute

org.eclipse.acute.feature/.project, org.eclipse.acute.feature/build.properties, org.eclipse.acute.feature/feature.properties, org.eclipse.acute.feature/feature.xml, pom.xml, repository/pom.xml, target-platform/target-platform.target
Build fails with the current one.
=> Fix jboss repository-utils repo declaration.

repository/category.xml, target-platform/target-platform.target
Move to latest Orbit and Oxygen RC2. Change site category.xml to not
hardcode versions.
=> Fix maven build.

org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizard.java, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizardPage.java
- Templates list updated after retrieved
- dotnet new command progress is displayed with monitor
=> Issue #22: Remove UI blocks

org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizard.java, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizardPage.java
- Set folder location to {workspace path}/NewDotnetProject{#}
- Set template to first in list if there are any
=> Issue #30: Pre-set folder and template

.travis.yml, settings.xml
=> Issue #14: Travis CI

org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizardPage.java
=> Issue #28: Template Table should have a border

org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetexport/AbstractExportWizardTest.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetexport/TestValidSelectionExport.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetnew/AbstractNewWizardTest.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetnew/AllNewTests.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetnew/TestProjectCreation.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestConfiguration.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestRun.java, org.eclipse.acute/plugin.xml, org.eclipse.acute/src/org/eclipse/acute/dotnetexport/DotnetExportWizard.java, org.eclipse.acute/src/org/eclipse/acute/dotnetexport/DotnetExportWizardPage.java, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizard.java, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizardPage.java, org.eclipse.acute/src/org/eclipse/acute/dotnetrun/DotnetRunDelegate.java
- All 'dotnet' and '.NET' texts switched to '.NET Core'
=> Issue #42 Rename references to .NET to .NET Core

target-platform/target-platform.target
=> Update TP to use release URL for Platform

org.eclipse.acute/META-INF/MANIFEST.MF, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewAccessor.java, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizard.java, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewWizardPage.java
=> Issue #59: Fix dotnet new command parameters separation

org.eclipse.acute.SWTBotTests/META-INF/MANIFEST.MF, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestConfiguration.java, org.eclipse.acute/src/org/eclipse/acute/dotnetrun/DotnetRunDelegate.java, org.eclipse.acute/src/org/eclipse/acute/dotnetrun/DotnetRunTab.java, org.eclipse.acute/src/org/eclipse/acute/dotnettest/DotnetTestDelegate.java, org.eclipse.acute/src/org/eclipse/acute/dotnettest/DotnetTestTab.java, target-platform/target-platform.target
=> Minor debug improvements

.travis.yml
=> Show mono and dotnet versions in log

org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestRun.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnettest/TestRun.java
The label of the running process was changed in a previous commit and
tests weren't updated accordingly
=> Fix tests for `dotnet test`

org.eclipse.acute.tests/META-INF/MANIFEST.MF, org.eclipse.acute.tests/projects/csproj/project2.0.csproj, org.eclipse.acute.tests/projects/csproj/test.cs, org.eclipse.acute.tests/src/org/eclipse/acute/tests/TestLSPIntegration.java
=> Issue #51: Test for .csproj

.travis.yml, org.eclipse.acute.omnisharpServer/pom.xml, org.eclipse.acute/src/org/eclipse/acute/OmnisharpStreamConnectionProvider.java
Better support for dotnet-core 2.0 projects,
embeds its own version of mono
=> Issue #51 : Update omnisharp-node-client

org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetexport/multipleFrameworks.csproj, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestConfiguration.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestRun.java, org.eclipse.acute/src/org/eclipse/acute/ProjectFileAccessor.java, org.eclipse.acute/src/org/eclipse/acute/dotnetrun/DotnetRunDelegate.java, org.eclipse.acute/src/org/eclipse/acute/dotnetrun/DotnetRunTab.java
Transition from dotnet run to dotnet exec
Signed-off-by: Lucas Bullen <lbullen@redhat.com>
=> Issue #62 `Run As > .Net Core Project` cannot kill child process

org.eclipse.acute/META-INF/MANIFEST.MF, org.eclipse.acute/src/org/eclipse/acute/ProjectFileAccessor.java, repository/category.xml, target-platform/target-platform.target
=> Issue #85: Use GSon

README.md
Removed mono-devel prerequisite
Added link to issues tab for Mac users
=> Removal of unnecessary prerequisite

org.eclipse.acute.tests/META-INF/MANIFEST.MF, org.eclipse.acute.tests/src/org/eclipse/acute/tests/TestLSPIntegration.java
=> Update to latest LSP4J api

Jenkinsfile
=> Issue #113: Pack and Sign bundles

org.eclipse.acute/build.properties, org.eclipse.acute/language-configurations/language-configuration.json, org.eclipse.acute/plugin.xml
This PR configure tm4e language configuration for C#. Today only "auto close" and "on enter" support are done.
=> Configure tm4e language configuration for C#.

pom.xml
Signed-off-by: Lucas Bullen <lbullen@redhat.com>
=> Update tycho version to 1.2.0

org.eclipse.acute/src/org/eclipse/acute/AcutePlugin.java, org.eclipse.acute/src/org/eclipse/acute/CommandJob.java, org.eclipse.acute/src/org/eclipse/acute/dotnetrun/DotnetRunDelegate.java, org.eclipse.acute/src/org/eclipse/acute/dotnettest/DotnetTestDelegate.java
- Remove build step, use `dotnet run` and --no-build flag instead
Signed-off-by: Lucas Bullen <lbullen@redhat.com>
=> #127 `dotnet exec` can be missing from the Launch

org.eclipse.acute/src/org/eclipse/acute/builder/IncrementalDotnetBuilder.java
- Only run builder if project folder exists and is a directory
- Able to cancel a build/clean
Signed-off-by: Lucas Bullen <lbullen@redhat.com>
=> Issue #136 Protection against builder errors

org.eclipse.acute.feature/feature.xml, pom.xml, roslynFragments/org.eclipse.acute.omnisharpServer.macosx.x86_64/pom.xml, roslynFragments/pom.xml
=> Issue #141 - Upgrade OmniSharp to get macOS support

Jenkinsfile
=> Set DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true for better CI

roslynFragments/pom.xml
=> Issue #144 - Use a working version of OmniSharp

org.eclipse.acute.SWTBotTests/META-INF/MANIFEST.MF, org.eclipse.acute.tests/META-INF/MANIFEST.MF, org.eclipse.acute.tests/build.properties, org.eclipse.acute.tests/src/org/eclipse/acute/tests/TestLSPIntegration.java, org.eclipse.acute/META-INF/MANIFEST.MF, org.eclipse.acute/build.properties, org.eclipse.acute/src/org/eclipse/acute/LaunchableAdapterFactory.java
* Deprecations
* Project config isssue
* Automatic-Module-Name
=> Fix various warnings.

Jenkinsfile
=> Tentative container-based Jenkinsfile

Jenkinsfile, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestConfiguration.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnettest/TestConfiguration.java
=> Start metacity from Jenkinsfile

Jenkinsfile, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetnew/AbstractNewWizardTest.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetnew/TestWizardUI.java, org.eclipse.acute.tests/src/org/eclipse/acute/tests/TestLSPIntegration.java, org.eclipse.acute/src/org/eclipse/acute/OmnisharpStreamConnectionProvider.java, pom.xml, roslynFragments/pom.xml
Cf https://dev.eclipse.org/ipzilla/show_bug.cgi?id=18798
=> Upgrade to Omnisharp-Roslyn 1.32.9

org.eclipse.acute.tests/src/org/eclipse/acute/tests/AbstractAcuteTest.java, org.eclipse.acute.tests/src/org/eclipse/acute/tests/TestLSPIntegration.java
More event checking and longer timeouts...
=> Attempt to fix TestLSPIntegration

netcoredbgFragments/pom.xml, org.eclipse.acute.SWTBotTests/META-INF/MANIFEST.MF, org.eclipse.acute.SWTBotTests/pom.xml, org.eclipse.acute.feature/feature.xml, org.eclipse.acute.msBuildServer/pom.xml, org.eclipse.acute.tests/META-INF/MANIFEST.MF, org.eclipse.acute.tests/pom.xml, org.eclipse.acute/META-INF/MANIFEST.MF, pom.xml, repository/category.xml, repository/pom.xml, roslynFragments/org.eclipse.acute.omnisharpServer.linux.x86/pom.xml, roslynFragments/org.eclipse.acute.omnisharpServer.linux.x86_64/pom.xml, roslynFragments/org.eclipse.acute.omnisharpServer.macosx.x86_64/pom.xml, roslynFragments/org.eclipse.acute.omnisharpServer.win32.x86/pom.xml, roslynFragments/org.eclipse.acute.omnisharpServer.win32.x86_64/pom.xml, roslynFragments/pom.xml, target-platform/pom.xml
=> Bump to 0.3.2.

org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/AllTests.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetexport/AbstractExportWizardTest.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetexport/TestValidSelectionExport.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetnew/TestWizardUI.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestConfiguration.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnetrun/TestRun.java, org.eclipse.acute.SWTBotTests/src/org/eclipse/acute/SWTBotTests/dotnettest/TestRun.java
=> Fix SWTBot tests

netcoredbgFragments/org.eclipse.acute.netcoredbg.linux.x86_64/pom.xml, netcoredbgFragments/org.eclipse.acute.netcoredbg.macosx.x86_64/pom.xml, netcoredbgFragments/org.eclipse.acute.netcoredbg.win32.x86_64/pom.xml, netcoredbgFragments/pom.xml, org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewAccessor.java
Small change to allow creating project using dotnet core 5.x
=> Introduce dotnet core 5.x

.mvn/extensions.xml, pom.xml
=> Update build dependencies

org.eclipse.acute/src/org/eclipse/acute/dotnetnew/DotnetNewAccessor.java
As output differs from version accept any line longer than 10 symbols '-' or ' ' as the line after which templates follow.
=> Fix project creation
